language: c++
before_install:
  - sudo chmod +x runtests.sh
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -qq
  - sudo apt-get install gdb # to capture backtrace of eventual failures
  - sudo apt-get install octave
  - sudo apt-get purge libopenblas-base # fixes PPA Octave 4.0 crash on Travis
before_script:
  - ulimit -c unlimited -S  # enable core dumps for Octave crash debugging
script:
  - ./runtests.sh /usr/bin/octave
after_failure:
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
  - gdb -c "$COREFILE" -ex "thread apply all bt" -ex "set pagination 0" -batch /usr/bin/octave-cli # print stack trace
