language: c++
before_install:
  - sudo chmod +x runtests.sh
  - sudo apt-get update --yes --force-yes
  - sudo apt-get install gdb # to capture backtrace of eventual failures
  # - sudo apt-get purge libopenblas-base # fixes PPA Octave 4.0 crash on Travis

  # add PPA repo to use latest GNU Octave release
  - sudo add-apt-repository ppa:octave/stable --yes

# dependencies
  - sudo apt-get install octave --yes --force-yes
  - sudo apt-get install liboctave-dev --yes --force-yes
  - sudo apt-get install gnuplot-x11

  - 
script:
  - ./runtests.sh /usr/bin/octave 
after_failure:
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
  - gdb -c "$COREFILE" -ex "thread apply all bt" -ex "set pagination 0" -batch /usr/bin/octave-cli # print stack trace
  - cat runtests.log
#  - tail runtests.err
