language: c++
before_install:
  - sudo chmod +x runtests.sh
  - sudo apt-get update -qq
  - sudo apt-get install gdb # to capture backtrace of eventual failures
  # - sudo apt-get purge libopenblas-base # fixes PPA Octave 4.0 crash on Travis

  # add PPA repo to use latest GNU Octave release
  - sudo add-apt-repository ppa:octave/stable --yes
  - sudo apt-get update --yes --force-yes

# dependencies
  - sudo apt-get install octave --yes --force-yes
  - sudo apt-get install liboctave-dev --yes --force-yes
  - sudo apt-get install coinor-libipopt-dev --yes --force-yes
  - sudo apt-get install git --yes --force-yes
  - sudo apt-get install -y mpich2 --yes --force-yes

# clone repository with IpOpt Interface
  - git clone https://github.com/ebertolazzi/mexIPOPT

# compile interface
  - mkoctfile --mex -ImexIPOPT/src -I/usr/include/coin -I/usr/include/octave_4*/octave mexIPOPT/src/ipopt.cc mexIPOPT/src/IpoptInterfaceCommon.cc -v -largeArrayDims -fPIC -O3 -DMATLAB_MEXFILE -DHAVE_CSTDDEF -DIPOPT_INTERFACE_MISSING_COPY_N -lipopt -std=gnu++11


before_script:
  - ulimit -c unlimited -S  # enable core dumps for Octave crash debugging
script:
  - ./runtests.sh /usr/bin/octave
after_failure:
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
  - gdb -c "$COREFILE" -ex "thread apply all bt" -ex "set pagination 0" -batch /usr/bin/octave-cli # print stack trace
